on:
  schedule:
  - cron: "0 3 * * *"
  workflow_dispatch:


jobs:
  get_daily:
    name: Get the daily challenge
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false 
        fetch-depth: 0 
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: npm install
    - name: Run main script
      run: ./run.sh
    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
  publish_page:
    name: Publish the daily challenge to the GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false 
        fetch-depth: 0 
        ref: 'pages'
    - name: Run main script
      run: ./run.sh
    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: pages
